FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV OLLAMA_HOST=0.0.0.0:11434

WORKDIR /app

RUN apt-get update && apt-get install -y \
    curl \
    wget \
    ca-certificates \
    bash dos2unix \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


RUN bash -c "$(curl -fsSL https://ollama.ai/install.sh)"

COPY app/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
RUN dos2unix /entrypoint.sh

EXPOSE 11434

CMD ["/entrypoint.sh"]