services:
  postgres_machiavelli_db:
    container_name: postgres_machiavelli_db
    image: postgres:15.8-alpine
    environment:
      POSTGRES_DB: 'machiavelli_db'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '7679:5432'  # external port mapped to the host
    networks:
      - machiavelli_network

  machiavelli_rabbitmq:
    image: rabbitmq:4.0.2-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./machiavelli/rabbitmq/data/:/var/lib/rabbitmq/
      - ./machiavelli/rabbitmq/log/:/var/log/rabbitmq/
    networks:
      - machiavelli_network

  machiavelli_idp_postgres:
    image: postgres:15.8-alpine
    volumes:
      - ./machiavelli/idp/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - machiavelli_network

  spring_container_team2:
    image: spring_container_team2:latest
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - postgres_machiavelli_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_machiavelli_db:5432/machiavelli_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI= http://localhost:8180/realms/machiavelli
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI= http://localhost:8180/realms/machiavelli/protocol/openid-connect/certs
    networks:
      - machiavelli_network

  machiavelli_idp_keycloak:
    image: quay.io/keycloak/keycloak:25.0.5
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KC_DB=postgres
      - KC_DB_URL_HOST=machiavelli_idp_postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
    command: start-dev
    ports:
      - "8180:8080"
    depends_on:
      - machiavelli_idp_postgres
    networks:
      - machiavelli_network

networks:
  machiavelli_network:
    driver: bridge
